### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by overfrequency** [MIPT-Oulu/KneeLocalizer#2]
Any idea why I'm having the following error?

```
    File "detector.py", line 12, in <module>  
    from oulukneeloc import SVM_MODEL_PATH
    ModuleNotFoundError: No module named 'oulukneeloc'
```

**Comment by lext** [comment]
@overfrequency this is a python package. Try to install it as

```
pip install -e .
```

when you are in the root directory

**Comment by soupault** [comment]
The README file should be updated with the propers steps.

**Comment by lext** [comment]
@overfrequency Could you please make a pull request regarding this issue?

**Comment by lext** [comment]
Or @soupault

**Comment by overfrequency** [comment]
@lext, @soupault   I have updated create_conda_env.sh.

**Comment by soupault** [comment]
@overfrequency looks good, thanks!
